name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read    

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - name: Get dependencies
        run: flutter pub get
      - name: Check code formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Static code analysis
        run: flutter analyze
      - name: Run unit tests
        run: flutter test --no-pub --test-randomize-ordering-seed=random
